<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Artium-PC" name="com.next.proj.nextG_proj.tests.DataProviderSearchingTest" tests="3" failures="1" timestamp="09 Jun 2019 21:01:24 GMT" time="26.200" errors="0">
  <testcase name="_003_searchFromMainLandingPage" time="13.128" classname="com.next.proj.nextG_proj.tests.DataProviderSearchingTest"/>
  <testcase name="_003_searchFromMainLandingPage" time="4.151" classname="com.next.proj.nextG_proj.tests.DataProviderSearchingTest"/>
  <testcase name="_003_searchFromMainLandingPage" time="8.921" classname="com.next.proj.nextG_proj.tests.DataProviderSearchingTest">
    <failure type="java.lang.AssertionError" message="Expecting to see &#039;Blue Nova Fides Signature Linen Suit&#039; in first result, but saw: Khaki Nova Fides Wool Blend Waistcoat
₪ 189
Add to Favourites expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expecting to see 'Blue Nova Fides Signature Linen Suit' in first result, but saw: Khaki Nova Fides Wool Blend Waistcoat
₪ 189
Add to Favourites expected [true] but found [false]
at il.co.topq.difido.ReportManager.onTestSuccess(ReportManager.java:209)
at il.co.topq.difido.ReportManagerHook.onTestSuccess(ReportManagerHook.java:30)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:70)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- _003_searchFromMainLandingPage -->
</testsuite> <!-- com.next.proj.nextG_proj.tests.DataProviderSearchingTest -->
